language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec rake spec
  - bundle exec rubocop
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
